name: Daily Product Hunt Scraper

on:
  schedule:
    # Run every day at 8:00 AM UTC
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Scraper Script
      id: scraper
      run: |
        python scraper.py > output.json
        cat output.json

    - name: Send Data to Zapier Webhook
      if: success()
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d @output.json \
          https://hooks.zapier.com/hooks/catch/XXXXXX/YYYYYY
